name: notebook
channels:
- conda-forge
dependencies:
  - nodejs
  - nb_conda_kernels
  - pip:
      - jupyterhub
      - notebook
      - jupyterlab
      - ipykernel
      - jupyterlab
      - git+https://github.com/jupyterhub/batchspawner.git@33b4a7b5134c3645911f9adfb3c97839cc76e668